---Notes Start---

---What is the dual TABLE in oracle? 
---The DUAL table is a special one-row, one-column table present by default in Oracle and other database installations. 
---In Oracle, the table has a single VARCHAR2(1) column called DUMMY that has a value of 'X'. 
---It is suitable for use in selecting a pseudo column such as SYSDATE or USER.

---Use TRUNCATE (drops all rows without deleting table) instead of DROP to drop tables
---Exists clause

---Notes End---

BEGIN
  FOR c IN ( SELECT table_name FROM user_tables)
  LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || c.table_name;
  END LOOP;
END;
/

CREATE TABLE runners(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100)
);
INSERT INTO runners
            SELECT 1, 'John Doe'    FROM dual
UNION ALL   SELECT 2, 'Jane Doe'    FROM dual
UNION ALL   SELECT 3, 'Alice Jones' FROM dual
UNION ALL   SELECT 4, 'Bobby Louis' FROM dual
UNION ALL   SELECT 5, 'Lisa Romero' FROM dual;
----------------------------------------------

CREATE TABLE races(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    event VARCHAR(100),
    winner_id NUMBER
);
INSERT INTO races
            SELECT 1, '100 meter dash', 2 FROM dual
UNION ALL   SELECT 2, '500 meter dash', 3 FROM dual
UNION ALL   SELECT 3, 'cross-country',  2 FROM dual
UNION ALL   SELECT 4, 'triathalon',  null FROM dual;
----------------------------------------------

CREATE TABLE Customers(
    id NUMBER,
    NAME VARCHAR(100),
    ReferredBy VARCHAR(100)
);
INSERT INTO Customers
            SELECT 1, 'John Doe',     null FROM dual
UNION ALL   SELECT 2, 'Jane SMith',   null FROM dual
UNION ALL   SELECT 3, 'Anne Jenkins', 2    FROM dual
UNION ALL   SELECT 4, 'Eric Branford',null FROM dual
UNION ALL   SELECT 5, 'Pat Richards', 1    FROM dual
UNION ALL   SELECT 6, 'Alice Barnes', 2    FROM dual;
-----------------------------------------------
